name: ocr
channels:
  - defaults
dependencies:
  - abseil-cpp=20230802.0
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - appnope=0.1.2
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=23.1.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - gtest=1.14.0
  - icu=73.1
  - idna=3.4
  - importlib_metadata=6.0.0
  - ipykernel=6.25.0
  - ipython=8.12.2
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numexpr=2.8.4
  - openai=0.27.4
  - openpyxl=3.0.10
  - openssl=3.0.12
  - orc=1.7.4
  - pandas=2.0.3
  - pandas-stubs=1.5.3.230203
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - plotly=5.9.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pympler=0.9
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyzmq=25.1.0
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - stack_data=0.2.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - types-pytz=2022.4.0.0
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - yarl=1.8.1
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - altair==5.1.2
      - backports-zoneinfo==0.2.1
      - blinker==1.7.0
      - cachetools==5.3.2
      - charset-normalizer==3.3.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - numpy==1.24.4
      - packaging==23.2
      - pdf2image==1.16.3
      - pillow==10.1.0
      - pip==23.3.1
      - protobuf==4.25.0
      - pyarrow==14.0.1
      - pydeck==0.8.1b0
      - pygments==2.16.1
      - rich==13.6.0
      - rpds-py==0.12.0
      - smmap==5.0.1
      - streamlit==1.28.1
      - tenacity==8.2.3
      - typing-extensions==4.8.0
      - tzlocal==5.2
      - urllib3==2.1.0
      - validators==0.22.0
      - zipp==3.17.0
